<?php
if (!defined('ABSPATH'))
    exit; // Exit if accessed directly
$locale = get_locale();
?>
<div id="ntdz_affiliate_page" class="ntdz-none ntdz-template-page">
    <span class="ntdz_h1_block"><span
            class="dashicons dashicons-networking"></span><?php esc_html_e('Affiliate Program', 'notifadz-by-adrenalead-web-push-notifications'); ?></span>
    <hr class="ntdz_dott">
    <div class="ntdz_box_row">
        <div class="ntdz_box_col75">
            <div class="ntdz_h3_block ntdz-large-text">
                <span><strong><span class="ntdz-emoji">&#128640; </span><?php esc_html_e('Boost your income with the affiliate program', 'notifadz-by-adrenalead-web-push-notifications'); ?></strong></span>
            </div>
            <p class="ntdz-medium-text">
                <?php esc_html_e('Adrenalead launches its first affiliate program for publishers.', 'notifadz-by-adrenalead-web-push-notifications'); ?>
            </p>
            <p class="ntdz-medium-text">
                <?php esc_html_e('How does it work? It`\'s very simple:', 'notifadz-by-adrenalead-web-push-notifications'); ?>
            </p>
            <ul>
                <li class="ntdz-medium-text"><span class="ntdz-emoji">&#x1F50E; </span><?php esc_html_e('Identify peers to whom you could recommend Notifadz', 'notifadz-by-adrenalead-web-push-notifications'); ?>
                </li>
                <li class="ntdz-medium-text"><span class="ntdz-emoji">&#128279; </span><?php esc_html_e('Share your personalized affiliate link', 'notifadz-by-adrenalead-web-push-notifications'); ?>
                </li>
                <li class="ntdz-medium-text"><span class="ntdz-emoji">&#128221; </span><?php esc_html_e('The referred publisher creates an account via your link, and is validated by our teams', 'notifadz-by-adrenalead-web-push-notifications'); ?>
                </li>
                <li class="ntdz-medium-text"><span class="ntdz-emoji">&#128176; </span><strong><?php esc_html_e('You earn 10% of the monthly revenues generated by your referred publishers!', 'notifadz-by-adrenalead-web-push-notifications'); ?></strong>
                </li>
            </ul>
            <p class="ntdz-medium-text">
                <?php esc_html_e('And more good news: all publishers who join the affiliate program by the end of the year 2024 will keep their 10% referred publishers revenue payout rate, for life!', 'notifadz-by-adrenalead-web-push-notifications'); ?>
            </p>
            <div style="margin-top:30px;" class="input-group">
                <?php if ($locale == 'fr_FR'): ?>
                    <a style="color:white!important" href="https://documentation-notifadz.notion.site/NOUVEAU-Programme-d-affiliation-7ae22270360748dea7035e2ef5ed6953" class="ntdz_button" target="_blank">
                        <?php esc_html_e('Learn more >>', 'notifadz-by-adrenalead-web-push-notifications'); ?>
                    </a>
                <?php else: ?>
                    <a style="color:white!important" href="https://documentation-notifadz.notion.site/NEW-Affiliate-program-5ceb6652af224535ad4528f09fae2678" class="ntdz_button" target="_blank">
                        <?php esc_html_e('Learn more >>', 'notifadz-by-adrenalead-web-push-notifications'); ?>
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>